### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by aflah02** [Anindya-Prithvi/fun_OS#2]
It should be descriptive over decriptive :)

**Comment by Anindya-Prithvi** [comment]
@aflah02 Please submit a patch ;)
😆

**Comment by aflah02** [comment]
> @aflah02 Please submit a patch ;) 😆

Sure I'm used to making patches :)

**Comment by aflah02** [comment]
Fixed with PR

**Comment by Anindya-Prithvi** [comment]
Thanks for your valuable contribution! I hope the readers will now be able to get full marks!!

**Comment by aflah02** [comment]
> Thanks for your valuable contribution! I hope the readers will now be able to get full marks!!

Wish I was SO LUCKY
